# Use Python base image with pip
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all contents into the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose Flask default port
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
